SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM DEPARTMENTS);

SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID NOT IN (SELECT LOCATION_ID FROM DEPARTMENTS);

SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM DEPARTMENTS) AND LOCATION_ID >1

