SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM DEPARTMENTS);

SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID NOT IN (SELECT LOCATION_ID FROM DEPARTMENTS);

SELECT CITY FROM LOCATIONS
WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM DEPARTMENTS) AND LOCATION_ID >1

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID), SUM(SALARY), AVG(SALARY)
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
GROUP BY DEPARTMENT_NAME, COUNTRY_NAME
ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID), SUM(SALARY), AVG(SALARY)
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
WHERE EMPLOYEE_ID NOT IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS)
GROUP BY DEPARTMENT_NAME, COUNTRY_NAME
ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;


SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID), SUM(SALARY), AVG(SALARY)
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
WHERE EMPLOYEE_ID NOT IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS)
GROUP BY DEPARTMENT_NAME, COUNTRY_NAME
ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;


SELECT COUNTRIES.COUNTRY_NAME AS "Pais", COUNT(EMPLOYEES.EMPLOYEE_ID) AS "Número dempleats"
FROM COUNTRIES JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY COUNTRIES.COUNTRY_NAME
ORDER BY COUNTRIES.COUNTRY_NAME ASC;

SELECT COUNTRIES.COUNTRY_NAME AS "Pais", COUNT(EMPLOYEES.EMPLOYEE_ID) AS "Número  dempleats",
CASE WHEN COUNT(EMPLOYEES.EMPLOYEE_ID) = 0 THEN 'Sense departaments'
ELSE 'Amb departaments' END AS "Estat" 
FROM COUNTRIES LEFT JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
LEFT JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
LEFT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY COUNTRIES.COUNTRY_NAME
ORDER BY COUNTRIES.COUNTRY_NAME ASC;




